#!/bin/bash

# Script for automatically updating the PPD files when data is committed to
# the git repositories of foomatic-db and foomatic-db-nonfree. The script also
# updates the copies of the Foomatic git repositories which provide the
# manufacturer-supplied ready-made PPD files for the OpenPrinting database.

# This script should be run as a cron job or triggered by git commits into
# foomatic-db and foomatic-db-nonfree.

# Adapted from the updatemysqlfromgit script from foomatic-webapp.

# Declare vars
BASE=/var/www/openprinting.org/openprinting
# Work directory for Foomatic-based backend scripts
WORKDIR=$BASE/ppd/foomatic

# Main part

(
  cd $WORKDIR || exit 1
  # Update packages from the version control system, then apply the
  # changed files to regenerate PPDs.

  # Package: foomatic-db
  if [ -d foomatic-db ] ; then
    cd foomatic-db || exit 1
    oldrev=$(git rev-parse --short HEAD)
    git pull
    rev=$(git rev-parse --short HEAD)
    if test "$rev" != "$oldrev"; then
      (
        cd $WORKDIR/foomatic-db-engine || exit 1
	# Currently just recompiles everything if a git commit occurred
	./foomatic-compiledb -j 4 -t ppd -f -d $BASE/ppd/ppd-files
	# TODO collate changed files
	# TODO regenerate PPDs based on changed files
      )
    fi
    cd ..
  fi

  # Package: foomatic-db-nonfree
  if [ -d foomatic-db-nonfree ] ; then
    cd foomatic-db-nonfree || exit 1
    oldrev=$(git rev-parse --short HEAD)
    git pull
    rev=$(git rev-parse --short HEAD)
    if test "$rev" != "$oldrev"; then
      (
        cd $WORKDIR/foomatic-db-engine || exit 1
	# Currently just recompiles everything if a git commit occurred
	./foomatic-compiledb -j 4 -t ppd -f -d $BASE/ppd/ppd-files
	# TODO collate changed files
	# TODO regenerate PPDs based on changed files
      )
    fi
    cd ..
  fi
)

