CREATE TABLE driver
(
	id VARCHAR(50) NOT NULL,
	name VARCHAR(50) NOT NULL,
	driver_group VARCHAR(50),
	locales TEXT,
        obsolete VARCHAR(50),
	pcdriver VARCHAR(8),
	url TINYTEXT,
	supplier VARCHAR(50),
	thirdpartysupplied BOOL NOT NULL DEFAULT 1,
	manufacturersupplied TINYTEXT,
	license TEXT,
	licensetext TEXT,
	licenselink TINYTEXT,
	nonfreesoftware BOOL NOT NULL DEFAULT 0,
	patents BOOL NOT NULL DEFAULT 0,
	shortdescription TEXT,
	max_res_x SMALLINT UNSIGNED,
	max_res_y SMALLINT UNSIGNED,
	color BOOL,
	text TINYINT UNSIGNED,
	lineart TINYINT UNSIGNED,
	graphics TINYINT UNSIGNED,
	photo TINYINT UNSIGNED,
	load_time TINYINT UNSIGNED,
	speed TINYINT UNSIGNED,
	execution ENUM('ghostscript','ijs','cups','opvp','uniprint','filter','postscript') NOT NULL,
	no_pjl BOOL NOT NULL,
	no_pageaccounting BOOL NOT NULL,
	prototype TEXT,
	pdf_prototype TEXT,
	ppdentry TEXT,
	comments TEXT,
	CONSTRAINT pkey PRIMARY KEY(id)
) ENGINE=InnoDB;