#!/bin/sh
if test "$1" = "-h" || test "$#" = "0"; then
    echo "Usage: `basename $0` <repodir>"
    echo "       `basename $0` <repodir> <rev>"
    echo "       `basename $0` <repodir> <oldrev> <rev>"
    echo
    echo "       Import changes on the BZR repository of foomatic-db and"
    echo "       foomatic-db-nonfree into the MySQL database."
    echo
    echo "       The first call imports the last commit, the second call"
    echo "       exactly the commit <rev>, and the third call all commits"
    echo "       which lead from the old state <oldrev> to the new state"
    echo "       <rev>."
    exit 1
fi
scriptdir=`dirname $0`
repodir=$1
if test "$#" = "1"; then
    rev=`cd $repodir; bzr revno`
    oldrev=`expr $rev - 1`
else
    rev=$2
    if test "$#" = "2"; then
	oldrev=`expr $rev - 1`
    else
	oldrev=$rev
	rev=$3
    fi
fi
echo "Importing changes between revision $oldrev and $rev from $repodir ..." 1>&2
op=:
for f in `cd $repodir; bzr status -r $oldrev..$rev`; do
    if [ "$f" = "added:" ]; then
	op0=:
	op1="php $scriptdir/xmltomysql.php"
	echo "Adding" 1>&2
    elif [ "$f" = "modified:" ]; then
	op0=:
	op1="php $scriptdir/xmltomysql.php"
	echo "Updating" 1>&2
    elif [ "$f" = "removed:" ]; then
	op0="php $scriptdir/remove.php"
	op1=:
	echo "Removing" 1>&2
    elif [ "$f" = "renamed:" ]; then
	op0="php $scriptdir/remove.php"
	op1="php $scriptdir/xmltomysql.php"
	echo "Renaming" 1>&2
    elif [ "$f" = "unknown:" ]; then
	echo "Ignoring" 1>&2
	op0=:
	op1=:
    elif `echo $f | egrep -q '^db/source/printer/.*\.xml$'`; then
	/bin/echo -en "  $f " 1>&2
	if [ -f $repodir/$f ]; then
	    echo "" 1>&2
	    $op1 -p $repodir/$f
	else
	    echo "X" 1>&2
	    $op0 -p $repodir/$f
	fi
    elif `echo $f | egrep -q '^db/source/driver/.*\.xml$'`; then
	/bin/echo -en "  $f " 1>&2
	if [ -f $repodir/$f ]; then
	    echo "" 1>&2
	    $op1 -d $repodir/$f
	else
	    echo "X" 1>&2
	    $op0 -d $repodir/$f
	fi
    elif `echo $f | egrep -q '^db/source/opt/.*\.xml$'`; then
	/bin/echo -en "  $f" 1>&2
	if [ -f $repodir/$f ]; then
	    echo "" 1>&2
	    $op1 -o $repodir/$f
	else
	    echo "X" 1>&2
	    $op0 -o $repodir/$f
	fi
    fi
done
echo "Done" 1>&2
