#!/bin/sh

# Auto conversion of all 32-bit and 64-bit x86 RPMs to DEBs and indexing
# of the DEB repository

# Needed to be installed (script runs only on x86_64/amd64):
# fakeroot, alien, linux32, ia32-libs, apt-ftparchive

# OBSOLETE. Just use "mkrepodeb" with '--all' option.

./mkrepodeb --all

