#!/bin/sh

# CUPS Filters
# ------------

version=1.0

# Build development snapshots

package=cups-filters
dir=
timestamp=`date +%Y%m%d`
downloadpath=/srv/www/openprinting/download/cups-filters/
mkdir -p $downloadpath
filename=${downloadpath}${package}-${version}-${timestamp}.tar.gz
oldfiles=`ls -1 ${downloadpath}${package}-${version}-????????.tar.gz 2> /dev/null | grep -v $filename`
currentlink=${downloadpath}${package}-${version}-current.tar.gz
tmpdir=`mktemp -u snapshot-XXXXXX`
mkdir $tmpdir
cd $tmpdir
bzr branch http://bzr.linuxfoundation.org/openprinting/${dir}/${package} > /dev/null 2>&1
if [ $? = 0 ] && [ -d ${package} ]; then
    cd ${package}
    aclocal > /dev/null 2>&1
    autoconf > /dev/null 2>&1
    rm -rf .bzr
    rm -rf autom*.cache
    cd ..
    ln -s ${package} ${package}-${version}-${timestamp}
    tar -czf $filename --dereference ${package}-${version}-${timestamp}
    if [ $? = 0 ] && [ -f ${filename} ]; then
	rm -f $oldfiles
	rm -f $currentlink
	ln -s $filename $currentlink
	chgrp www-data $filename $currentlink
	chmod g+rw $filename $currentlink
    else
	rm -f $filename
    fi
fi
cd ..
rm -rf $tmpdir

# Foomatic 4.0.x
# --------------

version=4.0

# Build stable release snapshots

# foomatic-db-engine

package=foomatic-db-engine
dir=foomatic-4.0
timestamp=`date +%Y%m%d`
downloadpath=/srv/www/openprinting/download/foomatic/
mkdir -p $downloadpath
filename=${downloadpath}${package}-${version}-${timestamp}.tar.gz
oldfiles=`ls -1 ${downloadpath}${package}-${version}-????????.tar.gz 2> /dev/null | grep -v $filename`
currentlink=${downloadpath}${package}-${version}-current.tar.gz
tmpdir=`mktemp -u snapshot-XXXXXX`
mkdir $tmpdir
cd $tmpdir
bzr branch http://bzr.linuxfoundation.org/openprinting//${dir}/${package} > /dev/null 2>&1
if [ $? = 0 ] && [ -d ${package} ]; then
    cd ${package}
    ./make_configure > /dev/null 2>&1
    rm -rf .bzr
    rm -rf autom*.cache
    cd ..
    ln -s ${package} ${package}-${version}-${timestamp}
    tar -czf $filename --dereference ${package}-${version}-${timestamp}
    if [ $? = 0 ] && [ -f ${filename} ]; then
	rm -f $oldfiles
	rm -f $currentlink
	ln -s $filename $currentlink
	chgrp www-data $filename $currentlink
	chmod g+rw $filename $currentlink
    else
	rm -f $filename
    fi
fi
cd ..
rm -rf $tmpdir

# foomatic-filters

package=foomatic-filters
dir=foomatic-4.0
timestamp=`date +%Y%m%d`
downloadpath=/srv/www/openprinting/download/foomatic/
mkdir -p $downloadpath
filename=${downloadpath}${package}-${version}-${timestamp}.tar.gz
oldfiles=`ls -1 ${downloadpath}${package}-${version}-????????.tar.gz 2> /dev/null | grep -v $filename`
currentlink=${downloadpath}${package}-${version}-current.tar.gz
tmpdir=`mktemp -u snapshot-XXXXXX`
mkdir $tmpdir
cd $tmpdir
bzr branch http://bzr.linuxfoundation.org/openprinting//${dir}/${package} > /dev/null 2>&1
if [ $? = 0 ] && [ -d ${package} ]; then
    cd ${package}
    ./make_configure > /dev/null 2>&1
    rm -rf .bzr
    rm -rf autom*.cache
    cd ..
    ln -s ${package} ${package}-${version}-${timestamp}
    tar -czf $filename --dereference ${package}-${version}-${timestamp}
    if [ $? = 0 ] && [ -f ${filename} ]; then
	rm -f $oldfiles
	rm -f $currentlink
	ln -s $filename $currentlink
	chgrp www-data $filename $currentlink
	chmod g+rw $filename $currentlink
    else
	rm -f $filename
    fi
fi
cd ..
rm -rf $tmpdir

# Build development snapshots

# foomatic-db-engine

package=foomatic-db-engine
dir=foomatic
timestamp=`date +%Y%m%d`
downloadpath=/srv/www/openprinting/download/foomatic/
mkdir -p $downloadpath
filename=${downloadpath}${package}-devel-${version}-${timestamp}.tar.gz
oldfiles=`ls -1 ${downloadpath}${package}-devel-${version}-????????.tar.gz 2> /dev/null | grep -v $filename`
currentlink=${downloadpath}${package}-devel-${version}-current.tar.gz
tmpdir=`mktemp -u snapshot-XXXXXX`
mkdir $tmpdir
cd $tmpdir
bzr branch http://bzr.linuxfoundation.org/openprinting//${dir}/${package} > /dev/null 2>&1
if [ $? = 0 ] && [ -d ${package} ]; then
    cd ${package}
    ./make_configure > /dev/null 2>&1
    rm -rf .bzr
    rm -rf autom*.cache
    cd ..
    ln -s ${package} ${package}-devel-${version}-${timestamp}
    tar -czf $filename --dereference ${package}-devel-${version}-${timestamp}
    if [ $? = 0 ] && [ -f ${filename} ]; then
	rm -f $oldfiles
	rm -f $currentlink
	ln -s $filename $currentlink
	chgrp www-data $filename $currentlink
	chmod g+rw $filename $currentlink
    else
	rm -f $filename
    fi
fi
cd ..
rm -rf $tmpdir

# foomatic-filters

package=foomatic-filters
dir=foomatic
timestamp=`date +%Y%m%d`
downloadpath=/srv/www/openprinting/download/foomatic/
mkdir -p $downloadpath
filename=${downloadpath}${package}-devel-${version}-${timestamp}.tar.gz
oldfiles=`ls -1 ${downloadpath}${package}-devel-${version}-????????.tar.gz 2> /dev/null | grep -v $filename`
currentlink=${downloadpath}${package}-devel-${version}-current.tar.gz
tmpdir=`mktemp -u snapshot-XXXXXX`
mkdir $tmpdir
cd $tmpdir
bzr branch http://bzr.linuxfoundation.org/openprinting//${dir}/${package} > /dev/null 2>&1
if [ $? = 0 ] && [ -d ${package} ]; then
    cd ${package}
    ./make_configure > /dev/null 2>&1
    rm -rf .bzr
    rm -rf autom*.cache
    cd ..
    ln -s ${package} ${package}-devel-${version}-${timestamp}
    tar -czf $filename --dereference ${package}-devel-${version}-${timestamp}
    if [ $? = 0 ] && [ -f ${filename} ]; then
	rm -f $oldfiles
	rm -f $currentlink
	ln -s $filename $currentlink
	chgrp www-data $filename $currentlink
	chmod g+rw $filename $currentlink
    else
	rm -f $filename
    fi
fi
cd ..
rm -rf $tmpdir

# Build database snapshots

# foomatic-db

package=foomatic-db
dir=foomatic
timestamp=`date +%Y%m%d`
downloadpath=/srv/www/openprinting/download/foomatic/
mkdir -p $downloadpath
filename=${downloadpath}${package}-${version}-${timestamp}.tar.gz
oldfiles=`ls -1 ${downloadpath}${package}-${version}-????????.tar.gz 2> /dev/null | grep -v $filename`
currentlink=${downloadpath}${package}-${version}-current.tar.gz
currentlink2=${downloadpath}${package}-current.tar.gz
tmpdir=`mktemp -u snapshot-XXXXXX`
mkdir $tmpdir
cd $tmpdir
bzr branch http://bzr.linuxfoundation.org/openprinting//${dir}/${package} > /dev/null 2>&1
if [ $? = 0 ] && [ -d ${package} ]; then
    cd ${package}
    ./make_configure > /dev/null 2>&1
    rm -rf .bzr
    rm -rf autom*.cache
    cd ..
    ln -s ${package} ${package}-${timestamp}
    tar -czf $filename --dereference ${package}-${timestamp}
    if [ $? = 0 ] && [ -f ${filename} ]; then
	rm -f $oldfiles
	rm -f $currentlink
	rm -f $currentlink2
	ln -s $filename $currentlink
	ln -s $filename $currentlink2
	chgrp www-data $filename $currentlink
	chmod g+rw $filename $currentlink
    else
	rm -f $filename
    fi
fi
cd ..
rm -rf $tmpdir

# foomatic-db-nonfree

package=foomatic-db-nonfree
dir=foomatic
timestamp=`date +%Y%m%d`
downloadpath=/srv/www/openprinting/download/foomatic/
mkdir -p $downloadpath
filename=${downloadpath}${package}-${timestamp}.tar.gz
oldfiles=`ls -1 ${downloadpath}${package}-????????.tar.gz 2> /dev/null | grep -v $filename`
currentlink=${downloadpath}${package}-current.tar.gz
tmpdir=`mktemp -u snapshot-XXXXXX`
mkdir $tmpdir
cd $tmpdir
bzr branch http://bzr.linuxfoundation.org/openprinting//${dir}/${package} > /dev/null 2>&1
if [ $? = 0 ] && [ -d ${package} ]; then
    cd ${package}
    ./make_configure > /dev/null 2>&1
    rm -rf .bzr
    rm -rf autom*.cache
    cd ..
    ln -s ${package} ${package}-${timestamp}
    tar -czf $filename --dereference ${package}-${timestamp}
    if [ $? = 0 ] && [ -f ${filename} ]; then
	rm -f $oldfiles
	rm -f $currentlink
	ln -s $filename $currentlink
	chgrp www-data $filename $currentlink
	chmod g+rw $filename $currentlink
    else
	rm -f $filename
    fi
fi
cd ..
rm -rf $tmpdir

exit 0
