#!/bin/bash

# Script for automatically updating the MySQL database when data got committed
# to the BZR repositories of foomatic-db and foomatic-db-nonfree. The script
# also updates the copies of the Foomatic BZR repositories which provide the
# manufacturer-supplied ready-made PPD files for the OpenPrinting database.

# This script should be run as a cron job or triggered by BZR commits into
# foomatic-db and foomatic-db-nonfree.

# Declare vars
BASE=/srv/www/openprinting
# Work directory for Foomatic-based backend scripts
WORKDIR=$BASE/foomatic

# This will return a single line with all necessary params in a 'key=value' form
CONF=`cd ../../foomatic &&  php ../dump_mysql_config.php | sed 's/: /=/g'`
# This will export 'server', 'user', 'password' and 'database' variables
export $CONF

DBPARAMS="--password=$password -u $user -h $server"
TMPFILE=`mktemp`

( cd $WORKDIR
    # Update packages from the version control system, then apply the
    # changed files to the MySQL database
    ## Package: foomatic-db
    if [ -d foomatic-db ]; then
	cd foomatic-db
	oldrev=`bzr revno`
	bzr pull
	rev=`bzr revno`
	if test "$rev" != "$oldrev"; then
	    ( cd $BASE
		./maint/scripts/importfrombzr $WORKDIR/foomatic-db $oldrev $rev
	    )

	    # Check which files inside 'source/PPD/' and 'source/driver/' folders were modified
	    # and regenerate corresponding driver packages
	    # For modified PPDs, we get drivers from the database
	    bzr diff -r $oldrev | grep 'source/PPD' | grep 'modified file\|added file\|removed file' \
		| sed 's%.*/%%' | sed 's%\.ppd.*%%' | sort -u | while read ppd
	    do
		driver=`mysql $DBPARAMS $database -e "SELECT default_driver FROM printer WHERE id='ppd'" | grep -v "default_driver"`
		echo $driver >>$TMPFILE
	    done

	    bzr diff -r $oldrev | grep 'source/driver' | grep 'modified file\|added file\|removed file' \
		| sed 's%.*/%%' | sed 's%\.xml.*%%' >>$TMPFILE

	    cat $TMPFILE | sort -u | grep -v '^[[:space:]]*$' | while read driver
	    do
		echo "Regenerating $driver"
		../foomatic-generate-package -d $driver
	    done
	fi
	cd ..
    fi
    ## Package: foomatic-db-nonfree
    if [ -d foomatic-db-nonfree ]; then
	cd foomatic-db-nonfree
	oldrev=`bzr revno`
	bzr pull
	rev=`bzr revno`
	if test "$rev" != "$oldrev"; then
	    ( cd $BASE
		./maint/scripts/importfrombzr $WORKDIR/foomatic-db-nonfree $oldrev $rev
	    )

	    # empty $TMPFILE after previous step
	    echo > $TMPFILE

	    # Check which files inside 'source/PPD/' and 'source/driver/' folders were modified
	    # and regenerate corresponding driver packages
	    bzr diff -r $oldrev | grep 'source/PPD' | grep 'modified file\|added file\|removed file' \
		| sed 's%.*/%%' | sed 's%\.ppd.*%%' | sort -u | while read ppd
	    do
		driver=`mysql $DBPARAMS $database -e "SELECT default_driver FROM printer WHERE id='ppd'" | grep -v "default_driver"`
		echo $driver >>$TMPFILE
	    done

	    bzr diff -r $oldrev | grep 'source/driver' | grep 'modified file\|added file\|removed file' \
		| sed 's%.*/%%' | sed 's%\.xml.*%%' >>$TMPFILE

	    cat $TMPFILE | sort -u | while read driver
	    do
		../foomatic-generate-package -d $driver
	    done
	fi
	cp -r db/source/PPD/* ../foomatic-db/db/source/PPD/
	cd ..
    fi
)

# Cleanup
rm -f $TMPFILE
