#!/bin/bash

# Script for automatically updating the BZR repositories from the MySQL
# database

# This script should be run as a cron job once a day

# Declare vars
BASE=/srv/www/openprinting-dev
#BASE=.
# Work directory for Foomatic-based backend scripts
#FOOMATICDIR=$BASE/foomatic/foomatic-db
FOOMATICDIR=$BASE/foomatic

cd $BASE
for repo in foomatic-db-nonfree foomatic-db; do
    pushed=0;
    while test "$pushed" = "0"; do
        # Import any BZR commit which happened in the meantime into the MySQL
        # database
	$BASE/maint/scripts/updatemysqlfrombzr

        # Create a temporary directory
	tmpdir= 
	#trap 'rm -rf $tmpdir' 0 1 2 13 15
	tmpdir=$(mktemp -d -t updatebzrfrommysql.XXXXXX)

        # Download the repository
	pushd $tmpdir > /dev/null 2>&1
	bzr branch http://bzr.openprinting.org/foomatic/$repo

	# Remove all XML and PPD files
	#rm -rf $repo/db/source
	rm -rf $repo/db/source/printer
	rm -rf $repo/db/source/driver
	rm -rf $repo/db/source/opt
	popd > /dev/null 2>&1
	
	# Export the current XML files from the MySQL database and also copy
	# the PPD files
	if test "$repo" = "foomatic-db-nonfree"; then 
	    #php $BASE/maint/scripts/exporttobzr.php -d $tmpdir -p $FOOMATICDIR -n
	    php $BASE/maint/scripts/exporttobzr.php -d $tmpdir -n
	else
	    #php $BASE/maint/scripts/exporttobzr.php -d $tmpdir -p $FOOMATICDIR -f
	    php $BASE/maint/scripts/exporttobzr.php -d $tmpdir -f
	fi
	#mkdir -p $tmpdir/$repo/db/source
	#cp -r $FOOMATICDIR/$repo/db/source/PPD $tmpdir/$repo/db/source

	# Look for new files with "bzr status" and add them to the
	# repository, also generate the entries for the ChangeLog file
	pushd $tmpdir/$repo > /dev/null 2>&1
	state=unknown
	touch $tmpdir/approved
	touch $tmpdir/added
	touch $tmpdir/modified
	touch $tmpdir/removed
	noadded=1
	nomodified=1
	noremoved=1
	changes=0
	for f in `bzr status`; do
	    if [ "$f" = "added:" ]; then
		state=modified
	    elif [ "$f" = "modified:" ]; then
		state=modified
	    elif [ "$f" = "removed:" ]; then
		state=removed
	    elif [ "$f" = "unknown:" ]; then
		state=new
	    elif `echo $f | egrep -q '^db/source/'`; then
		if test "$state" = "new"; then
		    bzr add $f;
		    changes=1
		    popd > /dev/null 2>&1
		    if test -z "`php $BASE/maint/scripts/changelogentry.php -f $f`"; then
			if test "$noadded" = "1"; then
			    echo -en "\t* $f" >> $tmpdir/added
			    noadded=0
			else
			    echo -en ",\n\t  $f" >> $tmpdir/added
			fi
		    else
			php $BASE/maint/scripts/changelogentry.php -f $f >> $tmpdir/approved
		    fi
		    pushd $tmpdir/$repo > /dev/null 2>&1
		elif test "$state" = "modified"; then
		    changes=1
		    if test "$nomodified" = "1"; then
			echo -en "\t* $f" >> $tmpdir/modified
			nomodified=0
		    else
			echo -en ",\n\t  $f" >> $tmpdir/modified
		    fi
		elif test "$state" = "removed"; then
		    changes=1
		    if test "$noremoved" = "1"; then
			echo -en "\t* $f" >> $tmpdir/removed
			noremoved=0
		    else
			echo -en ",\n\t  $f" >> $tmpdir/removed
		    fi
		fi
	    fi
	done

	if test "$changes" = "1"; then
	    # Add comment texts for ChangeLog
	    if test "$noadded" = "0"; then
		echo -en ":\n\t  New entries added to the MySQL database.\n\n" >> $tmpdir/added
	    fi
	    if test "$nomodified" = "0"; then
		echo -en ":\n\t  Entries modified in the MySQL database.\n\n" >> $tmpdir/modified
	    fi
	    if test "$noremoved" = "0"; then
		echo -en ":\n\t  Entries removed from the MySQL database.\n\n" >> $tmpdir/removed
	    fi

	    # Put ChangeLog together
	    echo -en `date --rfc-3339=date` > ChangeLog.new
	    echo -en '  OpenPrinting Web Server <webmaster@openprinting.org>\n\n' >> ChangeLog.new
	    cat $tmpdir/approved $tmpdir/added $tmpdir/modified $tmpdir/removed >> ChangeLog.new
	    cat ChangeLog >> ChangeLog.new
	    mv -f ChangeLog.new ChangeLog

	    # Commit the changes to the local repository
	    bzr commit -m "Daily snapshot of `date`"

	    # Push changes up to the server's repository
	    #bzr push bzr+ssh://`whoami`@bzr.linuxfoundation.org/srv/www/bzr/openprinting/foomatic/$repo && pushed=1
	    pushed=1
	else
	    # avoid infinite loop if there are no changes
	    pushed=1
	fi

	popd > /dev/null 2>&1

	#rm -rf $tmpdir
    done
done
