#!/bin/bash

# Script for automatically updating the BZR repositories from the MySQL
# database

# This script should be run as a cron job once a day

# Declare vars
BASE=/srv/www/openprinting-dev
#BASE=.
# Work directory for Foomatic-based backend scripts
#FOOMATICDIR=$BASE/foomatic/foomatic-db
FOOMATICDIR=$BASE/foomatic

cd $BASE
for repo in foomatic-db-nonfree foomatic-db; do
    pushed=0;
    while test "$pushed" = "0"; do
        # Import any BZR commit which happened in the meantime into the MySQL
        # database
	$BASE/maint/scripts/updatemysqlfrombzr

        # Create a temporary directory
	tmpdir= 
	#trap 'rm -rf $tmpdir' 0 1 2 13 15
	tmpdir=$(mktemp -d -t updatebzrfrommysql.XXXXXX)

        # Download the repository
	pushd $tmpdir > /dev/null 2>&1
	bzr branch http://bzr.openprinting.org/foomatic/$repo

	# Remove all XML and PPD files
	#rm -rf $repo/db/source
	rm -rf $repo/db/source/printer
	rm -rf $repo/db/source/driver
	rm -rf $repo/db/source/opt
	popd > /dev/null 2>&1
	
	# Export the current XML files from the MySQL database and also copy
	# the PPD files
	if test "$repo" = "foomatic-db-nonfree"; then 
	    #php $BASE/maint/scripts/exporttobzr.php -d $tmpdir -p $FOOMATICDIR -n
	    php $BASE/maint/scripts/exporttobzr.php -d $tmpdir -n
	else
	    #php $BASE/maint/scripts/exporttobzr.php -d $tmpdir -p $FOOMATICDIR -f
	    php $BASE/maint/scripts/exporttobzr.php -d $tmpdir -f
	fi
	#mkdir -p $tmpdir/$repo/db/source
	#cp -r $FOOMATICDIR/$repo/db/source/PPD $tmpdir/$repo/db/source

	# Look for new files with "bzr status" and add them to the
	# repository
	pushd $tmpdir/$repo > /dev/null 2>&1
	new=0
	for f in `bzr status`; do
	    if [ "$f" = "added:" ]; then
		new=0
	    elif [ "$f" = "modified:" ]; then
		new=0
	    elif [ "$f" = "removed:" ]; then
		new=0
	    elif [ "$f" = "unknown:" ]; then
		new=1
	    elif `echo $f | egrep -q '^db/source/'`; then
		if test "$new" = "1"; then
		    bzr add $f;
		fi
	    fi
	done

	# Commit the changes to the local repository
	bzr commit -m "Daily snapshot of `date`"

	# Push changes up to the server's repository
	# bzr push bzr+ssh://`whoami`@bzr.linuxfoundation.org/srv/www/bzr/openprinting/foomatic/$repo && pushed=1
	pushed=1

	popd > /dev/null 2>&1

	echo $tmpdir
	#rm -rf $tmpdir
    done
done
