#!/bin/bash

# Script for automatically updating the MySQL database when data got committed
# to the git repositories of foomatic-db and foomatic-db-nonfree. The script
# also updates the copies of the Foomatic git repositories which provide the
# manufacturer-supplied ready-made PPD files for the OpenPrinting database.

# This script should be run as a cron job or triggered by git commits into
# foomatic-db and foomatic-db-nonfree.

# Declare vars
BASE=/var/www/openprinting.org/openprinting
# Work directory for Foomatic-based backend scripts
WORKDIR=$BASE/foomatic

# Main part

(
  cd $WORKDIR || exit 1
  # Update packages from the version control system, then apply the
  # changed files to the MySQL database
  #
  ## Package: foomatic-db
  if [ -d foomatic-db ] ; then
    cd foomatic-db || exit 1
    oldrev=$(git rev-parse --short HEAD)
    git pull
    rev=$(git rev-parse --short HEAD)
    if test "$rev" != "$oldrev"; then
      (
        cd $BASE || exit 1
        ./maint/scripts/importfromgit $WORKDIR/foomatic-db "$oldrev" "$rev"
      )
    fi
    cd ..
  fi
  ## Package: foomatic-db-nonfree
  if [ -d foomatic-db-nonfree ] ; then
    cd foomatic-db-nonfree || exit 1
    oldrev=$(git rev-parse --short HEAD)
    git pull
    rev=$(git rev-parse --short HEAD)
    if test "$rev" != "$oldrev"; then
      (
        cd $BASE || exit 1
        ./maint/scripts/importfromgit $WORKDIR/foomatic-db-nonfree "$oldrev" "$rev"
      )
    fi
    cp -r db/source/PPD/* ../foomatic-db/db/source/PPD/
    cd ..
  fi
)
